#!/usr/bin/env python3
"""
bundle_web.py
Compresses or embeds web/index.html, web/style.css, web/app.js into C++ PROGMEM headers
so ESP32 web server can serve the entire remote interface directly out of flash memory.
"""

import os

def read_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def generate_web_assets_header(html_path, css_path, js_path, output_path):
    html_content = read_file(html_path)
    css_content = read_file(css_path)
    js_content = read_file(js_path)

    # Inline css and js into single HTML document for zero-latency single-file serving!
    inlined_html = html_content.replace(
        '<link rel="stylesheet" href="style.css" />',
        f'<style>\n{css_content}\n</style>'
    ).replace(
        '<script src="app.js"></script>',
        f'<script>\n{js_content}\n</script>'
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('/* Auto-generated by scripts/bundle_web.py - DO NOT EDIT MANUALLY */\n')
        f.write('#ifndef WEB_ASSETS_H\n#define WEB_ASSETS_H\n\n')
        f.write('#include <pgmspace.h>\n\n')
        f.write('static const char INDEX_HTML[] PROGMEM = R"rawliteral(\n')
        f.write(inlined_html)
        f.write('\n)rawliteral";\n\n')
        f.write('#endif // WEB_ASSETS_H\n')

    print(f"Successfully generated {output_path} ({len(inlined_html)} bytes).")

if __name__ == '__main__':
    generate_web_assets_header('web/index.html', 'web/style.css', 'web/app.js', 'include/web_assets.h')
