#!/usr/bin/env python3
"""
bundle_web.py
Compresses or embeds web/index.html, web/style.css, web/app.js,
manifest.json, sw.js, and icon.svg into C++ PROGMEM headers.
"""

import os

def read_file(filepath):
    if not os.path.exists(filepath):
        return ""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def generate_web_assets_header(web_dir, output_path):
    html_content = read_file(os.path.join(web_dir, 'index.html'))
    css_content = read_file(os.path.join(web_dir, 'style.css'))
    js_content = read_file(os.path.join(web_dir, 'app.js'))
    manifest_content = read_file(os.path.join(web_dir, 'manifest.json'))
    sw_content = read_file(os.path.join(web_dir, 'sw.js'))
    icon_content = read_file(os.path.join(web_dir, 'icon.svg'))

    # Inline css and js into single HTML document for zero-latency serving
    inlined_html = html_content.replace(
        '<link rel="stylesheet" href="style.css" />',
        f'<style>\n{css_content}\n</style>'
    ).replace(
        '<script src="app.js"></script>',
        f'<script>\n{js_content}\n</script>'
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('/* Auto-generated by scripts/bundle_web.py - DO NOT EDIT MANUALLY */\n')
        f.write('#ifndef WEB_ASSETS_H\n#define WEB_ASSETS_H\n\n')
        f.write('#include <pgmspace.h>\n\n')
        
        f.write('static const char INDEX_HTML[] PROGMEM = R"rawliteral(\n')
        f.write(inlined_html)
        f.write('\n)rawliteral";\n')
        f.write(f'static const size_t INDEX_HTML_LEN = {len(inlined_html.encode("utf-8"))};\n\n')

        f.write('static const char MANIFEST_JSON[] PROGMEM = R"rawliteral(\n')
        f.write(manifest_content)
        f.write('\n)rawliteral";\n')
        f.write(f'static const size_t MANIFEST_JSON_LEN = {len(manifest_content.encode("utf-8"))};\n\n')

        f.write('static const char SW_JS[] PROGMEM = R"rawliteral(\n')
        f.write(sw_content)
        f.write('\n)rawliteral";\n')
        f.write(f'static const size_t SW_JS_LEN = {len(sw_content.encode("utf-8"))};\n\n')

        f.write('static const char ICON_SVG[] PROGMEM = R"rawliteral(\n')
        f.write(icon_content)
        f.write('\n)rawliteral";\n')
        f.write(f'static const size_t ICON_SVG_LEN = {len(icon_content.encode("utf-8"))};\n\n')

        f.write('#endif // WEB_ASSETS_H\n')

    print(f"Successfully generated {output_path} (HTML: {len(inlined_html)}, Manifest: {len(manifest_content)}, SW: {len(sw_content)}, Icon: {len(icon_content)} bytes).")

if __name__ == '__main__':
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    web_directory = os.path.join(project_root, "web")
    output_header = os.path.join(project_root, "include", "web_assets.h")
    generate_web_assets_header(web_directory, output_header)
