#!/usr/bin/env python3
"""
generate_keymap.py
Parses Vendor_000d_Product_3838.kl and generates include/xgimi_keymap.h
for ESP32 BLE HID Remote firmware.
"""

import os
import re
import sys

# Linux input event keycodes to HID Keyboard Usage Codes (Page 0x07)
# and HID Consumer Control Usages (Page 0x0C)
LINUX_TO_HID = {
    1:   {"hid_page": 0x07, "hid_code": 0x29, "name": "KEY_ESC",         "desc": "Back / ESC"},
    28:  {"hid_page": 0x07, "hid_code": 0x28, "name": "KEY_ENTER",       "desc": "OK / Select"},
    62:  {"hid_page": 0x07, "hid_code": 0x3D, "name": "KEY_F4",          "desc": "Manual Focus"},
    65:  {"hid_page": 0x07, "hid_code": 0x40, "name": "KEY_F7",          "desc": "Source Input"},
    66:  {"hid_page": 0x07, "hid_code": 0x41, "name": "KEY_F8",          "desc": "Projector Settings"},
    67:  {"hid_page": 0x07, "hid_code": 0x42, "name": "KEY_F9",          "desc": "Manual Focus Left"},
    68:  {"hid_page": 0x07, "hid_code": 0x43, "name": "KEY_F10",         "desc": "Manual Focus Right"},
    87:  {"hid_page": 0x07, "hid_code": 0x44, "name": "KEY_F11",         "desc": "Autofocus"},
    88:  {"hid_page": 0x07, "hid_code": 0x45, "name": "KEY_F12",         "desc": "RC Low Battery"},
    102: {"hid_page": 0x07, "hid_code": 0x4A, "name": "KEY_HOME",        "desc": "Home"},
    103: {"hid_page": 0x07, "hid_code": 0x52, "name": "KEY_UP",          "desc": "D-Pad Up"},
    105: {"hid_page": 0x07, "hid_code": 0x50, "name": "KEY_LEFT",        "desc": "D-Pad Left"},
    106: {"hid_page": 0x07, "hid_code": 0x4F, "name": "KEY_RIGHT",       "desc": "D-Pad Right"},
    108: {"hid_page": 0x07, "hid_code": 0x51, "name": "KEY_DOWN",        "desc": "D-Pad Down"},
    113: {"hid_page": 0x0C, "hid_code": 0xE2, "name": "KEY_MUTE",        "desc": "Mute"},
    114: {"hid_page": 0x0C, "hid_code": 0xEA, "name": "KEY_VOLUMEDOWN",  "desc": "Volume Down"},
    115: {"hid_page": 0x0C, "hid_code": 0xE9, "name": "KEY_VOLUMEUP",    "desc": "Volume Up"},
    116: {"hid_page": 0x0C, "hid_code": 0x30, "name": "KEY_POWER",       "desc": "Power"},
    158: {"hid_page": 0x07, "hid_code": 0x29, "name": "KEY_BACK",        "desc": "Back"},
    172: {"hid_page": 0x07, "hid_code": 0x4A, "name": "KEY_HOMEPAGE",    "desc": "Home"},
    217: {"hid_page": 0x0C, "hid_code": 0x0221, "name": "KEY_SEARCH",    "desc": "Voice Assistant"},
    240: {"hid_page": 0x07, "hid_code": 0x65, "name": "KEY_MENU",        "desc": "Menu"},
    353: {"hid_page": 0x07, "hid_code": 0x28, "name": "KEY_SELECT",      "desc": "OK / Select"},
}

def parse_kl_file(kl_path):
    mappings = []
    if not os.path.exists(kl_path):
        print(f"Warning: {kl_path} not found. Using default internal mappings.")
        return mappings

    with open(kl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Format: key <linux_code> <android_action>
            match = re.match(r"^key\s+(\d+)\s+([A-Z0-9_]+)", line)
            if match:
                linux_code = int(match.group(1))
                android_action = match.group(2)
                if linux_code == 113:
                    android_action = "MUTE"
                hid_info = LINUX_TO_HID.get(linux_code, {
                    "hid_page": 0x07,
                    "hid_code": 0x00,
                    "name": f"KEY_{linux_code}",
                    "desc": android_action
                })
                mappings.append({
                    "linux_code": linux_code,
                    "android_action": android_action,
                    "hid_page": hid_info["hid_page"],
                    "hid_code": hid_info["hid_code"],
                    "desc": hid_info["desc"]
                })
    return mappings

def generate_header(mappings, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scripts/generate_keymap.py - DO NOT EDIT MANUALLY */\n")
        f.write("#ifndef XGIMI_KEYMAP_H\n#define XGIMI_KEYMAP_H\n\n")
        f.write("#include <stdint.h>\n\n")
        
        f.write("// XGIMI Remote Vendor ID & Product ID\n")
        f.write("#define XGIMI_VENDOR_ID  0x000D\n")
        f.write("#define XGIMI_PRODUCT_ID 0x3838\n")
        f.write('#define XGIMI_DEVICE_NAME "XGIMI RC pseudo"\n\n')

        f.write("struct XGIMIKeyMapping {\n")
        f.write("    const char* actionName;\n")
        f.write("    uint16_t linuxCode;\n")
        f.write("    uint8_t hidPage;   // 0x07 = Keyboard, 0x0C = Consumer Control\n")
        f.write("    uint16_t hidCode;\n")
        f.write("    const char* description;\n")
        f.write("};\n\n")

        f.write("static const XGIMIKeyMapping XGIMI_KEYMAP[] = {\n")
        for m in mappings:
            f.write(f'    {{ "{m["android_action"]}", {m["linux_code"]}, {hex(m["hid_page"])}, {hex(m["hid_code"])}, "{m["desc"]}" }},\n')
        f.write("};\n\n")

        f.write(f"static const size_t XGIMI_KEYMAP_SIZE = sizeof(XGIMI_KEYMAP) / sizeof(XGIMI_KEYMAP[0]);\n\n")
        f.write("#endif // XGIMI_KEYMAP_H\n")
    print(f"Successfully generated {output_path} with {len(mappings)} key mappings.")

if __name__ == "__main__":
    kl_file = sys.argv[1] if len(sys.argv) > 1 else "Vendor_000d_Product_3838.kl"
    out_file = sys.argv[2] if len(sys.argv) > 2 else "include/xgimi_keymap.h"
    mapped_keys = parse_kl_file(kl_file)
    generate_header(mapped_keys, out_file)
