/* Auto-generated by scripts/bundle_web.py - DO NOT EDIT MANUALLY */
#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <pgmspace.h>

static const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <title>XGIMI ESP32 Remote</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
:root {
  --bg-color: #000000;
  --surface-remote: #000000;
  --surface-card: #121316;
  --surface-btn: #18191d;
  --surface-btn-hover: #202227;
  --surface-btn-active: #2b2e36;
  --border-subtle: #24262d;
  --border-focus: #8ab4f8;
  --text-primary: #e8eaed;
  --text-secondary: #9aa0a6;
  --text-tertiary: #5f6368;
  --google-blue: #8ab4f8;
  --google-red: #f28b82;
  --google-green: #34a853;
  --google-yellow: #fdd663;
  --font-family: 'Outfit', -apple-system, BlinkMacSystemFont, 'Google Sans', Roboto, sans-serif;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  user-select: none;
  -webkit-tap-highlight-color: transparent;
}

html, body {
  height: 100%;
  width: 100%;
  background-color: var(--bg-color);
  color: var(--text-primary);
  font-family: var(--font-family);
  overflow-x: hidden;
}

body {
  min-height: 100vh;
  min-height: 100dvh;
  display: flex;
  justify-content: center;
  align-items: stretch;
  padding: env(safe-area-inset-top, 0px) env(safe-area-inset-right, 0px) env(safe-area-inset-bottom, 0px) env(safe-area-inset-left, 0px);
}

/* Remote Container - Full Screen Space Utilization */
.remote-container {
  position: relative;
  width: 100%;
  max-width: 480px;
  min-height: 100vh;
  min-height: 100dvh;
  background-color: var(--surface-remote);
  padding: 18px 20px 24px 20px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: 16px;
  margin: 0 auto;
}

/* On wider screens/desktops, give it a sleek framed appearance */
@media (min-width: 600px) {
  body {
    padding: 24px 16px;
    align-items: center;
  }
  
  .remote-container {
    min-height: 880px;
    height: 92vh;
    border: 1px solid var(--border-subtle);
    border-radius: 44px;
    padding: 28px 24px;
    box-shadow: 0 24px 60px rgba(0, 0, 0, 0.95);
  }
}

/* Header */
.remote-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 4px 6px;
  flex-shrink: 0;
}

.brand {
  display: flex;
  flex-direction: column;
}

.brand-title {
  font-size: 1.25rem;
  font-weight: 700;
  letter-spacing: 1.5px;
  color: var(--text-primary);
}

.brand-sub {
  font-size: 0.65rem;
  font-weight: 600;
  color: var(--text-secondary);
  letter-spacing: 1.2px;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 10px;
}

.btn-icon {
  background: var(--surface-btn);
  border: 1px solid var(--border-subtle);
  color: var(--text-primary);
  width: 42px;
  height: 42px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: background 0.15s ease, transform 0.15s ease;
}

.btn-icon:hover {
  background: var(--surface-btn-hover);
}

.btn-icon:active {
  background: var(--surface-btn-active);
  transform: scale(0.94);
}

.status-pill {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 14px;
  border-radius: 22px;
  background: var(--surface-btn);
  border: 1px solid var(--border-subtle);
  font-size: 0.75rem;
  font-weight: 500;
  color: var(--text-secondary);
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background-color: var(--google-yellow);
}

.status-pill.connected .status-dot {
  background-color: var(--google-green);
}

.status-pill.disconnected .status-dot {
  background-color: var(--google-red);
}

/* Base Buttons - Minimalist Google TV Style */
.btn {
  border: 1px solid var(--border-subtle);
  outline: none;
  cursor: pointer;
  border-radius: 20px;
  background: var(--surface-btn);
  color: var(--text-primary);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.12s ease, transform 0.12s ease, border-color 0.12s ease;
}

.btn:hover {
  background: var(--surface-btn-hover);
  border-color: #32353e;
}

.btn:active, .btn.active {
  background: var(--surface-btn-active);
  transform: scale(0.95);
  border-color: #40434e;
}

.icon {
  width: 24px;
  height: 24px;
}

/* Top Bar (Power, Focus, Misc Key, Source) */
.top-bar {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
  flex-shrink: 0;
}

.top-bar .btn {
  height: clamp(52px, 7.5vh, 62px);
}

.btn-power {
  color: var(--google-red);
  background: #171213;
  border-color: #321e20;
}

.btn-power:hover {
  background: #221618;
  border-color: #452427;
}

.btn-power:active {
  background: #2d181b;
}

.btn-focus {
  color: var(--google-blue);
}

.btn-focus:hover {
  border-color: var(--border-focus);
}

.btn-misc {
  color: var(--google-yellow);
}

.btn-source {
  color: var(--text-primary);
}

/* Navigation D-Pad (Google TV Circular Pad) */
.dpad-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 8px 0;
  flex: 1;
  min-height: 250px;
  max-height: 350px;
}

.dpad-ring {
  position: relative;
  width: clamp(230px, 68vw, 290px);
  height: clamp(230px, 68vw, 290px);
  border-radius: 50%;
  background: #131417;
  border: 1px solid var(--border-subtle);
}

.dpad-btn {
  position: absolute;
  border: none;
  outline: none;
  cursor: pointer;
  background: transparent;
  color: var(--text-secondary);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: color 0.12s ease, background 0.12s ease;
}

.dpad-btn .icon {
  width: 28px;
  height: 28px;
}

.dpad-btn:hover {
  color: var(--text-primary);
  background: rgba(255, 255, 255, 0.04);
}

.dpad-btn:active {
  background: rgba(255, 255, 255, 0.09);
  color: #fff;
}

.dpad-up {
  top: 8px;
  left: 50%;
  transform: translateX(-50%);
  width: clamp(74px, 22vw, 94px);
  height: clamp(58px, 16vw, 74px);
  border-radius: 38px 38px 14px 14px;
}

.dpad-down {
  bottom: 8px;
  left: 50%;
  transform: translateX(-50%);
  width: clamp(74px, 22vw, 94px);
  height: clamp(58px, 16vw, 74px);
  border-radius: 14px 14px 38px 38px;
}

.dpad-left {
  left: 8px;
  top: 50%;
  transform: translateY(-50%);
  width: clamp(58px, 16vw, 74px);
  height: clamp(74px, 22vw, 94px);
  border-radius: 38px 14px 14px 38px;
}

.dpad-right {
  right: 8px;
  top: 50%;
  transform: translateY(-50%);
  width: clamp(58px, 16vw, 74px);
  height: clamp(74px, 22vw, 94px);
  border-radius: 14px 38px 38px 14px;
}

.dpad-center {
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: clamp(82px, 24vw, 102px);
  height: clamp(82px, 24vw, 102px);
  border-radius: 50%;
  background: #202227;
  border: 1px solid #2e313a;
  color: var(--text-primary);
  font-weight: 600;
  font-size: 1.05rem;
  letter-spacing: 0.5px;
  transition: transform 0.12s ease, background 0.12s ease;
}

.dpad-center:hover {
  background: #282a31;
  color: #fff;
}

.dpad-center:active {
  transform: translate(-50%, -50%) scale(0.93);
  background: #31353f;
}

/* Function Row (Back, Home, Menu, Voice) */
.function-row {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 10px;
  flex-shrink: 0;
}

.btn-pill {
  height: clamp(54px, 7.8vh, 66px);
  flex-direction: column;
  gap: 5px;
  font-size: 0.65rem;
  font-weight: 600;
  letter-spacing: 0.5px;
  border-radius: 20px;
}

.btn-pill .icon {
  width: 20px;
  height: 20px;
}

.btn-voice {
  color: var(--google-blue);
}

.btn-voice:hover {
  border-color: var(--border-focus);
}

/* Volume Control Bar (Vol -, Mute, Vol +) */
.volume-bar {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 10px;
  align-items: center;
  background: #131417;
  border-radius: 28px;
  padding: 6px 8px;
  border: 1px solid var(--border-subtle);
  height: clamp(52px, 7.5vh, 62px);
  flex-shrink: 0;
}

.btn-vol, .btn-vol-mute {
  height: clamp(40px, 5.8vh, 48px);
  gap: 6px;
  font-size: 0.74rem;
  font-weight: 600;
  border-radius: 22px;
  background: var(--surface-btn);
  border: 1px solid var(--border-subtle);
  display: flex;
  align-items: center;
  justify-content: center;
}

.btn-vol-mute {
  color: var(--text-secondary);
}

.btn-vol-mute:hover {
  color: #fff;
  border-color: #3d414d;
}

.btn-vol-mute:active {
  color: var(--google-red);
}

.btn-vol .icon, .btn-vol-mute .icon {
  width: 18px;
  height: 18px;
}

/* Footer */
.remote-footer {
  text-align: center;
  font-size: 0.68rem;
  color: var(--text-tertiary);
  letter-spacing: 0.8px;
  padding-top: 4px;
  flex-shrink: 0;
}

/* Modal Overlay & Card (Google TV Dark Sheet) */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.85);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  z-index: 100;
  display: flex;
  justify-content: center;
  align-items: center;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.2s ease;
  padding: 16px;
}

.modal-overlay.open {
  opacity: 1;
  pointer-events: auto;
}

.modal-card {
  width: 100%;
  max-width: 420px;
  max-height: 90vh;
  overflow-y: auto;
  background: var(--surface-card);
  border: 1px solid var(--border-subtle);
  border-radius: 28px;
  padding: 24px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.9);
  display: flex;
  flex-direction: column;
  gap: 18px;
  scrollbar-width: thin;
  scrollbar-color: #33363f transparent;
}

.modal-card::-webkit-scrollbar {
  width: 6px;
}

.modal-card::-webkit-scrollbar-thumb {
  background: #33363f;
  border-radius: 3px;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid #1f2127;
  padding-bottom: 12px;
}

.modal-title {
  font-size: 0.88rem;
  font-weight: 700;
  letter-spacing: 1.2px;
  color: var(--text-primary);
}

.btn-close {
  background: var(--surface-btn);
  border: 1px solid var(--border-subtle);
  color: var(--text-secondary);
  width: 34px;
  height: 34px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.3rem;
  line-height: 1;
  cursor: pointer;
  transition: all 0.15s ease;
}

.btn-close:hover {
  color: #fff;
  background: var(--surface-btn-hover);
}

.modal-body {
  display: flex;
  flex-direction: column;
  gap: 18px;
}

.pair-status-box {
  background: #18191e;
  border-radius: 16px;
  padding: 14px;
  border: 1px solid var(--border-subtle);
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.pair-status-header {
  display: flex;
  align-items: center;
  gap: 10px;
  font-weight: 600;
  font-size: 0.85rem;
}

.status-indicator-dot {
  width: 9px;
  height: 9px;
  border-radius: 50%;
  background-color: var(--google-yellow);
}

.pair-info-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.76rem;
  color: var(--text-secondary);
}

.pair-info-row strong {
  color: var(--text-primary);
}

.action-section {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.section-title {
  font-size: 0.65rem;
  font-weight: 700;
  letter-spacing: 1px;
  color: var(--text-secondary);
}

.btn-modal {
  width: 100%;
  height: 46px;
  border-radius: 16px;
  font-weight: 600;
  font-size: 0.82rem;
  gap: 8px;
  background: var(--surface-btn);
  border: 1px solid var(--border-subtle);
}

.btn-action-primary {
  background: #172030;
  border: 1px solid #2d3e5c;
  color: var(--google-blue);
}

.btn-action-primary:hover {
  background: #1d283c;
  border-color: var(--google-blue);
}

.btn-action-danger {
  background: #241416;
  border: 1px solid #482326;
  color: var(--google-red);
}

.btn-action-danger:hover {
  background: #2f181b;
  border-color: var(--google-red);
}

.pin-input-group {
  display: flex;
  gap: 8px;
  width: 100%;
}

.pin-input-group input {
  flex: 1;
  min-width: 0;
  height: 46px;
  background: #18191e;
  border: 1px solid var(--border-subtle);
  border-radius: 14px;
  padding: 0 14px;
  color: var(--text-primary);
  font-family: var(--font-family);
  font-size: 0.95rem;
  letter-spacing: 2px;
  outline: none;
  transition: border-color 0.15s ease;
}

.pin-input-group input:focus {
  border-color: var(--border-focus);
}

.pin-input-group .btn-modal {
  width: auto;
  min-width: 105px;
  height: 46px;
  flex-shrink: 0;
  white-space: nowrap;
}

.wifi-input-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
}

.wifi-input-group input {
  width: 100%;
  height: 44px;
  background: #18191e;
  border: 1px solid var(--border-subtle);
  border-radius: 14px;
  padding: 0 14px;
  color: var(--text-primary);
  font-family: var(--font-family);
  font-size: 0.88rem;
  outline: none;
  transition: border-color 0.15s ease;
}

.wifi-input-group input:focus {
  border-color: var(--border-focus);
}

.wifi-input-group .btn-modal {
  margin-top: 4px;
}

</style>
  <link rel="manifest" href="/manifest.json" />
  <meta name="theme-color" content="#0b0d13" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="apple-mobile-web-app-title" content="XGIMI Remote" />
  <link rel="icon" type="image/svg+xml" href="/icon.svg" />
  <link rel="apple-touch-icon" href="/icon.svg" />
</head>

<body>
  <div class="remote-container">
    <!-- Header / Status Bar -->
    <header class="remote-header">
      <div class="brand">
        <span class="brand-title">XGIMI</span>
        <span class="brand-sub">ESP32 REMOTE</span>
      </div>
      <div class="header-actions">
        <button class="btn-icon" id="installPwaBtn" title="Install App (PWA)" style="display: none;">
          <svg viewBox="0 0 24 24" class="icon">
            <path fill="currentColor"
              d="M19.35,10.04C18.67,6.59 15.64,4 12,4C9.11,4 6.6,5.64 5.35,8.04C2.34,8.36 0,10.91 0,14A6,6 0 0,0 6,20H19A5,5 0 0,0 24,15C24,12.36 21.95,10.22 19.35,10.04M17,13L12,18L7,13H10V9H14V13H17Z" />
          </svg>
        </button>
        <button class="btn-icon" id="openPairingBtn" title="Pairing & Accessories">
          <svg viewBox="0 0 24 24" class="icon">
            <path fill="currentColor"
              d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M11,7V13H13V7H11M11,15V17H13V15H11Z" />
          </svg>
        </button>
        <div class="status-pill" id="statusPill">
          <span class="status-dot"></span>
          <span class="status-text" id="statusText">Connecting...</span>
        </div>
      </div>
    </header>

    <!-- Top Action Buttons (Power, Focus, XGIMI Settings/Misc, Input Source) -->
    <div class="top-bar">
      <button class="btn btn-power" data-action="KPPOWER" title="Power">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor"
            d="M13,3H11V13H13M17.83,5.17L16.41,6.59C18.05,7.91 19,9.9 19,12A7,7 0 0,1 12,19A7,7 0 0,1 5,12C5,9.9 5.95,7.91 7.58,6.58L6.17,5.17C4.21,6.82 3,9.26 3,12A9,9 0 0,0 12,21A9,9 0 0,0 21,12C21,9.26 19.79,6.82 17.83,5.17Z" />
        </svg>
      </button>
      <button class="btn btn-focus" data-action="FOCUS_AUTO" title="Autofocus">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor"
            d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M12,6A6,6 0 0,0 6,12A6,6 0 0,0 12,18A6,6 0 0,0 18,12A6,6 0 0,0 12,6M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z" />
        </svg>
      </button>
      <button class="btn btn-misc" data-action="XGIMI_MISCKEY" title="XGIMI Settings (Misc Key)">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor"
            d="M12,15.5A3.5,3.5 0 0,1 8.5,12A3.5,3.5 0 0,1 12,8.5A3.5,3.5 0 0,1 15.5,12A3.5,3.5 0 0,1 12,15.5M19.43,12.97C19.47,12.65 19.5,12.33 19.5,12C19.5,11.67 19.47,11.34 19.43,11L21.54,9.37C21.73,9.22 21.78,8.95 21.66,8.73L19.66,5.27C19.54,5.05 19.27,4.96 19.05,5.05L16.56,6.05C16.04,5.66 15.5,5.32 14.87,5.07L14.49,2.42C14.46,2.18 14.25,2 14,2H10C9.75,2 9.54,2.18 9.51,2.42L9.13,5.07C8.5,5.32 7.96,5.66 7.44,6.05L4.95,5.05C4.73,4.96 4.46,5.05 4.34,5.27L2.34,8.73C2.21,8.95 2.27,9.22 2.46,9.37L4.57,11C4.53,11.34 4.5,11.67 4.5,12C4.5,12.33 4.53,12.65 4.57,12.97L2.46,14.63C2.27,14.78 2.21,15.05 2.34,15.27L4.34,18.73C4.46,18.95 4.73,19.03 4.95,18.95L7.44,17.94C7.96,18.34 8.5,18.68 9.13,18.93L9.51,21.58C9.54,21.82 9.75,22 10,22H14C14.25,22 14.46,21.82 14.49,21.58L14.87,18.93C15.5,18.68 16.04,18.34 16.56,17.94L19.05,18.95C19.27,19.03 19.54,18.95 19.66,18.73L21.66,15.27C21.78,15.05 21.73,14.78 21.54,14.63L19.43,12.97Z" />
        </svg>
      </button>
      <button class="btn btn-source" data-action="XGIMI_SOURCE" title="Input Source">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor"
            d="M21,3H3A2,2 0 0,0 1,5V19A2,2 0 0,0 3,21H21A2,2 0 0,0 23,19V5A2,2 0 0,0 21,3M21,19H3V5H21V19M16,16L20,12L16,8V11H8V13H16V16Z" />
        </svg>
      </button>
    </div>

    <!-- Navigation D-Pad Ring -->
    <div class="dpad-wrapper">
      <div class="dpad-ring">
        <button class="dpad-btn dpad-up" data-action="DPAD_UP" title="Up">
          <svg viewBox="0 0 24 24" class="icon">
            <path fill="currentColor" d="M7.41,15.41L12,10.83L16.59,15.41L18,14L12,8L6,14L7.41,15.41Z" />
          </svg>
        </button>
        <button class="dpad-btn dpad-left" data-action="DPAD_LEFT" title="Left">
          <svg viewBox="0 0 24 24" class="icon">
            <path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" />
          </svg>
        </button>
        <button class="dpad-btn dpad-center" data-action="DPAD_CENTER" title="OK / Select">
          <span>OK</span>
        </button>
        <button class="dpad-btn dpad-right" data-action="DPAD_RIGHT" title="Right">
          <svg viewBox="0 0 24 24" class="icon">
            <path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" />
          </svg>
        </button>
        <button class="dpad-btn dpad-down" data-action="DPAD_DOWN" title="Down">
          <svg viewBox="0 0 24 24" class="icon">
            <path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
          </svg>
        </button>
      </div>
    </div>

    <!-- Android / Remote Function Keys (Back, Home, Menu, Voice) -->
    <div class="function-row">
      <button class="btn btn-pill" data-action="BACK" title="Back">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor" d="M20,11H7.83L13.42,5.41L12,4L4,12L12,20L13.41,18.59L7.83,13H20V11Z" />
        </svg>
        <span>BACK</span>
      </button>

      <button class="btn btn-pill" data-action="HOME" title="Home">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor" d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z" />
        </svg>
        <span>HOME</span>
      </button>

      <button class="btn btn-pill" data-action="MENU" title="Menu">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor" d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" />
        </svg>
        <span>MENU</span>
      </button>

      <button class="btn btn-pill btn-voice" data-action="VOICE_ASSIST" title="Voice Assistant">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor"
            d="M12,2A3,3 0 0,1 15,5V11A3,3 0 0,1 12,14A3,3 0 0,1 9,11V5A3,3 0 0,1 12,2M19,11C19,14.53 16.39,17.44 13,17.93V21H11V17.93C7.61,17.44 5,14.53 5,11H7A5,5 0 0,0 12,16A5,5 0 0,0 17,11H19Z" />
        </svg>
        <span>VOICE</span>
      </button>
    </div>

    <!-- Volume Control Bar (Vol -, Mute, Vol +) -->
    <div class="volume-bar">
      <button class="btn btn-vol" data-action="VOLUME_DOWN" title="Volume Down">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor" d="M5,9V15H9L14,20V4L9,9H5M11,15.83L8.83,13.66H7V10.34H8.83L11,8.17V15.83Z" />
        </svg>
        <span>VOL -</span>
      </button>
      <button class="btn btn-vol-mute" data-action="MUTE" title="Mute Toggle">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor"
            d="M12,4L9.91,6.09L12,8.18M4.27,3L3,4.27L7.73,9H3V15H7L12,20V13.27L16.25,17.53C15.58,18.04 14.83,18.46 14,18.7V20.77C15.38,20.45 16.63,19.82 17.68,18.96L19.73,21L21,19.73L4.27,3M19,12C19,12.94 18.8,13.82 18.46,14.64L19.97,16.15C20.62,14.91 21,13.5 21,12C21,7.72 18,4.14 14,3.23V5.29C16.89,6.15 19,8.83 19,12M16.5,12C16.5,10.23 15.5,8.71 14,7.97V16.02C15.5,15.29 16.5,13.76 16.5,12M3,9V15H7L12,20V4L7,9H3Z" />
        </svg>
        <span>MUTE</span>
      </button>
      <button class="btn btn-vol" data-action="VOLUME_UP" title="Volume Up">
        <svg viewBox="0 0 24 24" class="icon">
          <path fill="currentColor"
            d="M14,3.23V5.29C16.89,6.15 19,8.83 19,12C19,15.17 16.89,17.84 14,18.7V20.77C18,19.86 21,16.28 21,12C21,7.72 18,4.14 14,3.23M16.5,12C16.5,10.23 15.5,8.71 14,7.97V16.02C15.5,15.29 16.5,13.76 16.5,12M3,9V15H7L12,20V4L7,9H3Z" />
        </svg>
        <span>VOL +</span>
      </button>
    </div>

    <!-- Footer Information -->
    <footer class="remote-footer">
      <span>Target: Vendor 0x000D / PID 0x3838</span>
    </footer>
  </div>

  <!-- Pairing Management Modal -->
  <div class="modal-overlay" id="pairingModal">
    <div class="modal-card">
      <div class="modal-header">
        <span class="modal-title">PAIRING & ACCESSORIES</span>
        <button class="btn-close" id="closePairingBtn">&times;</button>
      </div>

      <div class="modal-body">
        <div class="pair-status-box">
          <div class="pair-status-header">
            <span class="status-indicator-dot" id="modalStatusDot"></span>
            <span class="pair-status-state" id="modalStatusText">Checking BLE Status...</span>
          </div>
          <div class="pair-info-row">
            <span>Bonded Devices:</span> <strong id="modalBondedCount">0</strong>
          </div>
          <div class="pair-info-row">
            <span>Peer Address:</span> <strong id="modalPeerAddr">None</strong>
          </div>
        </div>

        <!-- BLE Pairing Actions -->
        <div class="action-section">
          <span class="section-title">BLUETOOTH REMOTE PAIRING</span>
          <button class="btn btn-modal btn-action-primary" id="startPairingBtn">
            <svg viewBox="0 0 24 24" class="icon">
              <path fill="currentColor"
                d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M11,7V13H13V7H11M11,15V17H13V15H11Z" />
            </svg>
            <span>Start BLE Pairing Mode</span>
          </button>

          <button class="btn btn-modal btn-action-danger" id="clearBondsBtn">
            <svg viewBox="0 0 24 24" class="icon">
              <path fill="currentColor"
                d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" />
            </svg>
            <span>Clear Saved Bluetooth Bonds</span>
          </button>
        </div>

        <!-- Wi-Fi PIN Pairing Input -->
        <div class="action-section">
          <span class="section-title">WI-FI TV REMOTE PIN AUTHENTICATION</span>
          <div class="pin-input-group">
            <input type="text" id="pinInput" maxlength="6" placeholder="Enter PIN code" autocomplete="off" />
            <button class="btn btn-modal btn-action-primary" id="submitPinBtn">Pair PIN</button>
          </div>
        </div>

        <!-- Home Wi-Fi Network Setup -->
        <div class="action-section">
          <span class="section-title">CONNECT TO HOME WI-FI</span>
          <div class="pair-info-row" style="margin-bottom: 6px;">
            <span>Current Status:</span> <strong id="wifiStatusText">Checking...</strong>
          </div>
          <div class="wifi-input-group">
            <input type="text" id="wifiSsidInput" placeholder="Home Wi-Fi SSID" autocomplete="off" />
            <input type="password" id="wifiPassInput" placeholder="Wi-Fi Password" autocomplete="off" />
            <button class="btn btn-modal btn-action-primary" id="saveWifiBtn">Connect & Save</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
/**
 * XGIMI ESP32 BLE Remote & Pairing Web Application
 */

document.addEventListener('DOMContentLoaded', () => {
  const statusPill = document.getElementById('statusPill');
  const statusText = document.getElementById('statusText');
  const openPairingBtn = document.getElementById('openPairingBtn');
  const closePairingBtn = document.getElementById('closePairingBtn');
  const pairingModal = document.getElementById('pairingModal');

  const modalStatusDot = document.getElementById('modalStatusDot');
  const modalStatusText = document.getElementById('modalStatusText');
  const modalBondedCount = document.getElementById('modalBondedCount');
  const modalPeerAddr = document.getElementById('modalPeerAddr');

  const startPairingBtn = document.getElementById('startPairingBtn');
  const clearBondsBtn = document.getElementById('clearBondsBtn');
  const pinInput = document.getElementById('pinInput');
  const submitPinBtn = document.getElementById('submitPinBtn');
  const installPwaBtn = document.getElementById('installPwaBtn');

  let deferredPrompt = null;
  let socket = null;
  let isConnected = false;

  // PWA Service Worker Registration & Install Prompt
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('/sw.js')
        .then(reg => console.log('[PWA] ServiceWorker registered:', reg.scope))
        .catch(err => console.log('[PWA] ServiceWorker failed:', err));
    });
  }

  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault();
    deferredPrompt = e;
    if (installPwaBtn) {
      installPwaBtn.style.display = 'flex';
    }
  });

  if (installPwaBtn) {
    installPwaBtn.addEventListener('click', async () => {
      if (deferredPrompt) {
        deferredPrompt.prompt();
        const { outcome } = await deferredPrompt.userChoice;
        console.log('[PWA] User choice:', outcome);
        deferredPrompt = null;
        installPwaBtn.style.display = 'none';
      } else {
        alert('To install on iPhone/iPad: Tap the Share icon (box with up arrow) in Safari and tap "Add to Home Screen".');
      }
    });
  }

  window.addEventListener('appinstalled', () => {
    console.log('[PWA] App successfully installed');
    if (installPwaBtn) {
      installPwaBtn.style.display = 'none';
    }
  });

  // Initialize WebSocket or HTTP polling fallback
  function initConnection() {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = `${protocol}//${window.location.host}/ws`;

    try {
      socket = new WebSocket(wsUrl);

      socket.onopen = () => {
        setConnectedState(true, 'Connected');
        fetchPairingStatus();
      };

      socket.onclose = () => {
        setConnectedState(false, 'Reconnecting...');
        setTimeout(initConnection, 2000);
      };

      socket.onerror = () => {
        setConnectedState(false, 'HTTP Fallback Mode');
      };

      socket.onmessage = (event) => {
        try {
          const msg = JSON.parse(event.data);
          if (msg.type === 'pairing_status') {
            updatePairingUI(msg);
          } else if (msg.status === 'ble_connected') {
            setConnectedState(true, 'BLE Connected');
          } else if (msg.status === 'ble_disconnected') {
            setConnectedState(false, 'BLE Disconnected');
          }
        } catch (e) {
          console.log('WS msg:', event.data);
        }
      };
    } catch (err) {
      setConnectedState(false, 'HTTP Mode');
    }
  }

  function setConnectedState(connected, text) {
    isConnected = connected;
    statusText.textContent = text;
    if (connected) {
      statusPill.classList.remove('disconnected');
      statusPill.classList.add('connected');
    } else {
      statusPill.classList.remove('connected');
      statusPill.classList.add('disconnected');
    }
  }

  function updatePairingUI(status) {
    modalBondedCount.textContent = status.bonded_count ?? 0;
    modalPeerAddr.textContent = status.peer_address ?? 'None';

    if (status.connected) {
      modalStatusText.textContent = 'Paired & Connected to Projector';
      modalStatusDot.style.backgroundColor = '#00e676';
    } else if (status.advertising) {
      modalStatusText.textContent = 'BLE Pairing Mode Active (Discoverable)';
      modalStatusDot.style.backgroundColor = '#00f2fe';
    } else {
      modalStatusText.textContent = 'Not Connected / Idle';
      modalStatusDot.style.backgroundColor = '#ff4b4b';
    }
  }

  function fetchPairingStatus() {
    fetch('/api/pair/status')
      .then(res => res.json())
      .then(data => updatePairingUI(data))
      .catch(err => console.error('Failed fetching pairing status:', err));
  }

  // Send action to ESP32
  function triggerAction(actionName) {
    if ('vibrate' in navigator) {
      navigator.vibrate(25);
    }

    if (socket && socket.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'key_press', action: actionName }));
    } else {
      fetch(`/api/press?action=${encodeURIComponent(actionName)}`, { method: 'POST' })
        .catch(err => console.error('Failed sending key press:', err));
    }
  }

  // Pairing Modal Event Handlers
  openPairingBtn.addEventListener('click', () => {
    pairingModal.classList.add('open');
    fetchPairingStatus();
    fetchWifiStatus();
  });

  closePairingBtn.addEventListener('click', () => {
    pairingModal.classList.remove('open');
  });

  pairingModal.addEventListener('click', (e) => {
    if (e.target === pairingModal) {
      pairingModal.classList.remove('open');
    }
  });

  startPairingBtn.addEventListener('click', () => {
    fetch('/api/pair/start', { method: 'POST' })
      .then(res => res.json())
      .then(data => {
        alert('BLE Pairing Mode Enabled for 60s! On your XGIMI Projector, go to Settings -> Remotes & Accessories -> Add Accessory and select XGIMI-RC-pseudo.');
        fetchPairingStatus();
      })
      .catch(err => alert('Failed starting BLE pairing mode: ' + err));
  });

  clearBondsBtn.addEventListener('click', () => {
    if (confirm('Are you sure you want to clear all stored Bluetooth bonds?')) {
      fetch('/api/pair/clear', { method: 'POST' })
        .then(res => res.json())
        .then(data => {
          alert('Cleared all saved Bluetooth bonds!');
          fetchPairingStatus();
        })
        .catch(err => alert('Failed clearing bonds: ' + err));
    }
  });

  submitPinBtn.addEventListener('click', () => {
    const pin = pinInput.value.trim();
    if (!pin) {
      alert('Please enter a PIN code.');
      return;
    }
    fetch('/api/pair/pin', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: `pin=${encodeURIComponent(pin)}`
    })
      .then(res => res.json())
      .then(data => {
        alert(`PIN '${pin}' submitted successfully!`);
        pinInput.value = '';
      })
      .catch(err => alert('Failed submitting PIN: ' + err));
  });

  const wifiStatusText = document.getElementById('wifiStatusText');
  const wifiSsidInput = document.getElementById('wifiSsidInput');
  const wifiPassInput = document.getElementById('wifiPassInput');
  const saveWifiBtn = document.getElementById('saveWifiBtn');

  function fetchWifiStatus() {
    if (!wifiStatusText) return;
    fetch('/api/wifi/status')
      .then(res => res.json())
      .then(data => {
        if (data.connected) {
          wifiStatusText.textContent = `Connected to ${data.ssid} (${data.ip})`;
          wifiStatusText.style.color = '#00e676';
        } else {
          wifiStatusText.textContent = 'Not connected to Home Wi-Fi';
          wifiStatusText.style.color = '#ff4b4b';
        }
      })
      .catch(err => console.error('Failed fetching Wi-Fi status:', err));
  }

  if (saveWifiBtn) {
    saveWifiBtn.addEventListener('click', () => {
      const ssid = wifiSsidInput.value.trim();
      const pass = wifiPassInput.value.trim();
      if (!ssid) {
        alert('Please enter a Wi-Fi SSID.');
        return;
      }
      saveWifiBtn.textContent = 'Connecting...';
      saveWifiBtn.disabled = true;

      fetch('/api/wifi/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: `ssid=${encodeURIComponent(ssid)}&pass=${encodeURIComponent(pass)}`
      })
        .then(res => res.json())
        .then(data => {
          saveWifiBtn.textContent = 'Connect & Save';
          saveWifiBtn.disabled = false;
          if (data.connected) {
            alert(`Success! Connected to '${ssid}'.\nHome IP: http://${data.ip}\nmDNS URL: http://xgimi-remote.local`);
            fetchWifiStatus();
          } else {
            alert(`Failed connecting to '${ssid}'. Please check credentials.`);
            fetchWifiStatus();
          }
        })
        .catch(err => {
          saveWifiBtn.textContent = 'Connect & Save';
          saveWifiBtn.disabled = false;
          alert('Network request error: ' + err);
        });
    });
  }

  // Attach event listeners to all remote buttons
  const buttons = document.querySelectorAll('[data-action]');
  buttons.forEach(button => {
    const actionName = button.getAttribute('data-action');
    
    button.addEventListener('pointerdown', (e) => {
      e.preventDefault();
      button.classList.add('active');
      triggerAction(actionName);
    });

    button.addEventListener('pointerup', () => {
      button.classList.remove('active');
    });

    button.addEventListener('pointerleave', () => {
      button.classList.remove('active');
    });
  });

  // Physical Keyboard shortcut support
  window.addEventListener('keydown', (e) => {
    if (e.repeat) return;
    let action = null;
    switch (e.key) {
      case 'ArrowUp': action = 'DPAD_UP'; break;
      case 'ArrowDown': action = 'DPAD_DOWN'; break;
      case 'ArrowLeft': action = 'DPAD_LEFT'; break;
      case 'ArrowRight': action = 'DPAD_RIGHT'; break;
      case 'Enter': action = 'DPAD_CENTER'; break;
      case 'Escape': case 'Backspace': action = 'BACK'; break;
      case 'Home': action = 'HOME'; break;
      case 'm': case 'M': action = 'MENU'; break;
      case 'f': case 'F': action = 'FOCUS_AUTO'; break;
      case 'g': case 'G': action = 'FOCUS_MAN_NEW'; break;
      case '[': action = 'FOCUS_LEFT'; break;
      case ']': action = 'FOCUS_RIGHT'; break;
      case 's': case 'S': action = 'XGIMI_MISCKEY'; break;
      case '+': action = 'VOLUME_UP'; break;
      case '-': action = 'VOLUME_DOWN'; break;
    }
    if (action) {
      const btn = document.querySelector(`[data-action="${action}"]`);
      if (btn) {
        btn.classList.add('active');
        setTimeout(() => btn.classList.remove('active'), 200);
      }
      triggerAction(action);
    }
  });

  initConnection();
});

</script>
</body>

</html>
)rawliteral";
static const size_t INDEX_HTML_LEN = 35473;

static const char MANIFEST_JSON[] PROGMEM = R"rawliteral(
{
  "name": "XGIMI Remote",
  "short_name": "XGIMI Remote",
  "description": "ESP32 Bluetooth Remote for XGIMI Projector",
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "orientation": "portrait-primary",
  "background_color": "#0b0d13",
  "theme_color": "#0b0d13",
  "categories": ["utilities", "entertainment"],
  "icons": [
    {
      "src": "/icon.svg",
      "sizes": "any",
      "type": "image/svg+xml",
      "purpose": "any"
    },
    {
      "src": "/icon.svg",
      "sizes": "512x512",
      "type": "image/svg+xml",
      "purpose": "maskable"
    }
  ]
}

)rawliteral";
static const size_t MANIFEST_JSON_LEN = 589;

static const char SW_JS[] PROGMEM = R"rawliteral(
const CACHE_NAME = 'xgimi-remote-v1';
const ASSETS_TO_CACHE = [
  '/',
  '/manifest.json',
  '/icon.svg'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS_TO_CACHE);
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  // Pass WebSocket and API requests directly to network
  if (event.request.url.includes('/api/') || event.request.url.includes('/ws')) {
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((networkResponse) => {
        if (networkResponse && networkResponse.status === 200) {
          const responseClone = networkResponse.clone();
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(event.request, responseClone);
          });
        }
        return networkResponse;
      })
      .catch(() => {
        return caches.match(event.request).then((cachedResponse) => {
          return cachedResponse || caches.match('/');
        });
      })
  );
});

)rawliteral";
static const size_t SW_JS_LEN = 1328;

static const char ICON_SVG[] PROGMEM = R"rawliteral(
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <defs>
    <radialGradient id="bgGrad" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#161b26"/>
      <stop offset="100%" stop-color="#0b0d13"/>
    </radialGradient>
    <linearGradient id="neonCyan" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#00f2fe"/>
      <stop offset="100%" stop-color="#4facfe"/>
    </linearGradient>
    <linearGradient id="neonPurple" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#7f53ac"/>
      <stop offset="100%" stop-color="#647eee"/>
    </linearGradient>
    <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="12" result="blur" />
      <feComposite in="SourceGraphic" in2="blur" operator="over" />
    </filter>
  </defs>

  <!-- Background -->
  <rect width="512" height="512" rx="110" fill="url(#bgGrad)" />
  <rect width="500" height="500" x="6" y="6" rx="104" fill="none" stroke="rgba(255,255,255,0.1)" stroke-width="2"/>

  <!-- Glowing Outer Ring -->
  <circle cx="256" cy="220" r="140" fill="none" stroke="url(#neonCyan)" stroke-width="12" opacity="0.4" filter="url(#glow)"/>
  <circle cx="256" cy="220" r="140" fill="none" stroke="url(#neonCyan)" stroke-width="6" />

  <!-- Inner Projector Lens Rings -->
  <circle cx="256" cy="220" r="105" fill="none" stroke="url(#neonPurple)" stroke-width="8" opacity="0.6"/>
  <circle cx="256" cy="220" r="70" fill="rgba(0, 242, 254, 0.15)"/>
  <circle cx="256" cy="220" r="45" fill="url(#neonCyan)"/>
  <circle cx="240" cy="204" r="15" fill="#ffffff" opacity="0.8"/>

  <!-- Remote Beam Rays -->
  <path d="M170 380 L342 380" stroke="url(#neonCyan)" stroke-width="10" stroke-linecap="round"/>
  <path d="M210 410 L302 410" stroke="url(#neonPurple)" stroke-width="8" stroke-linecap="round"/>
  <path d="M236 440 L276 440" stroke="rgba(255,255,255,0.4)" stroke-width="6" stroke-linecap="round"/>
</svg>

)rawliteral";
static const size_t ICON_SVG_LEN = 1997;

#endif // WEB_ASSETS_H
