/* Auto-generated by scripts/bundle_web.py - DO NOT EDIT MANUALLY */
#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <pgmspace.h>

static const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <title>XGIMI ESP32 Remote</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
:root {
  --bg-color: #0b0d13;
  --panel-bg: rgba(22, 27, 38, 0.75);
  --glass-border: rgba(255, 255, 255, 0.1);
  --accent-cyan: #00f2fe;
  --accent-blue: #4facfe;
  --accent-purple: #7f53ac;
  --accent-magenta: #647eee;
  --accent-red: #ff4b4b;
  --accent-green: #00e676;
  --text-main: #f0f3f8;
  --text-muted: #8a94a6;
  --btn-glass: rgba(255, 255, 255, 0.06);
  --btn-glass-hover: rgba(255, 255, 255, 0.12);
  --btn-glass-active: rgba(0, 242, 254, 0.25);
  --shadow-glow: 0 0 25px rgba(0, 242, 254, 0.2);
  --font-family: 'Outfit', -apple-system, BlinkMacSystemFont, sans-serif;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  user-select: none;
  -webkit-tap-highlight-color: transparent;
}

body {
  background-color: var(--bg-color);
  color: var(--text-main);
  font-family: var(--font-family);
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow-x: hidden;
  padding: 16px;
}

/* Background Ambient Glow */
.background-glow {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 350px;
  height: 600px;
  background: radial-gradient(circle, rgba(79, 172, 254, 0.15) 0%, rgba(127, 83, 172, 0.1) 40%, rgba(11, 13, 19, 0) 70%);
  pointer-events: none;
  z-index: 0;
  filter: blur(40px);
}

/* Remote Outer Container */
.remote-container {
  position: relative;
  z-index: 1;
  width: 100%;
  max-width: 400px;
  background: var(--panel-bg);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border: 1px solid var(--glass-border);
  border-radius: 32px;
  padding: 24px;
  box-shadow: 0 20px 50px rgba(0, 0, 0, 0.6), inset 0 1px 1px rgba(255, 255, 255, 0.1);
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Header */
.remote-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.brand {
  display: flex;
  flex-direction: column;
}

.brand-title {
  font-size: 1.25rem;
  font-weight: 700;
  letter-spacing: 2px;
  background: linear-gradient(135deg, var(--accent-cyan), var(--accent-blue));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.brand-sub {
  font-size: 0.65rem;
  font-weight: 600;
  color: var(--text-muted);
  letter-spacing: 1.5px;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 10px;
}

.btn-icon {
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: var(--accent-cyan);
  width: 36px;
  height: 36px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
}

.btn-icon:hover {
  background: rgba(0, 242, 254, 0.2);
  transform: scale(1.05);
}

.status-pill {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  border-radius: 20px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.08);
  font-size: 0.75rem;
  font-weight: 500;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background-color: #ffb703;
  box-shadow: 0 0 8px #ffb703;
  transition: background-color 0.3s, box-shadow 0.3s;
}

.status-pill.connected .status-dot {
  background-color: var(--accent-green);
  box-shadow: 0 0 10px var(--accent-green);
}

.status-pill.disconnected .status-dot {
  background-color: var(--accent-red);
  box-shadow: 0 0 10px var(--accent-red);
}

/* Buttons Base */
.btn {
  border: none;
  outline: none;
  cursor: pointer;
  border-radius: 16px;
  background: var(--btn-glass);
  color: var(--text-main);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  border: 1px solid var(--glass-border);
}

.btn:hover {
  background: var(--btn-glass-hover);
  transform: translateY(-2px);
}

.btn:active, .btn.active {
  transform: translateY(1px) scale(0.96);
  background: var(--btn-glass-active);
  border-color: var(--accent-cyan);
  box-shadow: 0 0 15px rgba(0, 242, 254, 0.3);
}

.icon {
  width: 22px;
  height: 22px;
}

/* Top Bar */
.top-bar {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
}

.top-bar .btn {
  height: 52px;
}

.btn-power {
  background: rgba(255, 75, 75, 0.15);
  color: var(--accent-red);
  border-color: rgba(255, 75, 75, 0.3);
}

.btn-power:hover {
  background: rgba(255, 75, 75, 0.25);
  box-shadow: 0 0 15px rgba(255, 75, 75, 0.4);
}

/* Focus Engine Section */
.focus-card {
  background: rgba(0, 0, 0, 0.25);
  border-radius: 20px;
  padding: 14px;
  border: 1px solid rgba(255, 255, 255, 0.05);
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-title {
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 1.5px;
  color: var(--accent-cyan);
}

.focus-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
}

.btn-autofocus {
  background: linear-gradient(135deg, rgba(0, 242, 254, 0.2), rgba(79, 172, 254, 0.2));
  border: 1px solid rgba(0, 242, 254, 0.4);
  color: #fff;
  height: 48px;
  gap: 8px;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 1px;
}

.btn-autofocus:hover {
  box-shadow: var(--shadow-glow);
}

.btn-manualfocus {
  background: linear-gradient(135deg, rgba(127, 83, 172, 0.2), rgba(100, 126, 238, 0.2));
  border: 1px solid rgba(127, 83, 172, 0.4);
  color: #fff;
  height: 48px;
  gap: 8px;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 1px;
}

.btn-stepper {
  height: 42px;
  gap: 6px;
  font-size: 0.75rem;
  font-weight: 600;
}

/* D-Pad Ring */
.dpad-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 10px 0;
}

.dpad-ring {
  position: relative;
  width: 200px;
  height: 200px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.08);
  box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.5);
}

.dpad-btn {
  position: absolute;
  border: none;
  outline: none;
  cursor: pointer;
  background: rgba(255, 255, 255, 0.05);
  color: var(--text-main);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.15s ease;
}

.dpad-btn:hover {
  background: rgba(0, 242, 254, 0.2);
  color: var(--accent-cyan);
}

.dpad-btn:active {
  transform: scale(0.92);
  background: var(--accent-cyan);
  color: #000;
}

.dpad-up {
  top: 6px;
  left: 50%;
  transform: translateX(-50%);
  width: 60px;
  height: 50px;
  border-radius: 30px 30px 10px 10px;
}

.dpad-down {
  bottom: 6px;
  left: 50%;
  transform: translateX(-50%);
  width: 60px;
  height: 50px;
  border-radius: 10px 10px 30px 30px;
}

.dpad-left {
  left: 6px;
  top: 50%;
  transform: translateY(-50%);
  width: 50px;
  height: 60px;
  border-radius: 30px 10px 10px 30px;
}

.dpad-right {
  right: 6px;
  top: 50%;
  transform: translateY(-50%);
  width: 50px;
  height: 60px;
  border-radius: 10px 30px 30px 10px;
}

.dpad-center {
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 68px;
  height: 68px;
  border-radius: 50%;
  background: linear-gradient(135deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.04));
  border: 1px solid rgba(255, 255, 255, 0.15);
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.4);
  font-weight: 700;
  font-size: 0.95rem;
  letter-spacing: 1px;
}

.dpad-center:hover {
  background: linear-gradient(135deg, var(--accent-cyan), var(--accent-blue));
  color: #000;
}

/* Function Buttons (Back, Home, Menu, Voice) */
.function-row {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px;
}

.btn-pill {
  height: 46px;
  flex-direction: column;
  gap: 4px;
  font-size: 0.65rem;
  font-weight: 600;
  letter-spacing: 0.5px;
}

.btn-pill .icon {
  width: 18px;
  height: 18px;
}

.btn-voice {
  color: var(--accent-cyan);
  border-color: rgba(0, 242, 254, 0.2);
}

/* Volume Control Bar */
.volume-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: rgba(0, 0, 0, 0.2);
  border-radius: 20px;
  padding: 6px 12px;
  border: 1px solid rgba(255, 255, 255, 0.05);
}

.vol-indicator {
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 2px;
  color: var(--text-muted);
}

.btn-vol {
  height: 42px;
  padding: 0 16px;
  gap: 6px;
  font-size: 0.75rem;
  font-weight: 600;
}

/* Footer */
.remote-footer {
  text-align: center;
  font-size: 0.65rem;
  color: var(--text-muted);
  letter-spacing: 1px;
}

/* Modal Overlay & Card */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.75);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  z-index: 100;
  display: flex;
  justify-content: center;
  align-items: center;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.3s ease;
  padding: 16px;
}

.modal-overlay.open {
  opacity: 1;
  pointer-events: auto;
}

.modal-card {
  width: 100%;
  max-width: 380px;
  background: var(--panel-bg);
  border: 1px solid var(--glass-border);
  border-radius: 28px;
  padding: 20px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.8);
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.modal-title {
  font-size: 0.85rem;
  font-weight: 700;
  letter-spacing: 1.5px;
  color: var(--accent-cyan);
}

.btn-close {
  background: none;
  border: none;
  color: var(--text-muted);
  font-size: 1.5rem;
  cursor: pointer;
}

.modal-body {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.pair-status-box {
  background: rgba(0, 0, 0, 0.3);
  border-radius: 16px;
  padding: 14px;
  border: 1px solid rgba(255, 255, 255, 0.05);
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.pair-status-header {
  display: flex;
  align-items: center;
  gap: 10px;
  font-weight: 600;
  font-size: 0.85rem;
}

.status-indicator-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background-color: #ffb703;
}

.pair-info-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.75rem;
  color: var(--text-muted);
}

.pair-info-row strong {
  color: var(--text-main);
}

.action-section {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.section-title {
  font-size: 0.65rem;
  font-weight: 700;
  letter-spacing: 1px;
  color: var(--text-muted);
}

.btn-modal {
  width: 100%;
  height: 44px;
  border-radius: 14px;
  font-weight: 600;
  font-size: 0.8rem;
  gap: 8px;
}

.btn-action-primary {
  background: linear-gradient(135deg, rgba(0, 242, 254, 0.2), rgba(79, 172, 254, 0.2));
  border: 1px solid rgba(0, 242, 254, 0.3);
  color: #fff;
}

.btn-action-danger {
  background: rgba(255, 75, 75, 0.15);
  border: 1px solid rgba(255, 75, 75, 0.3);
  color: var(--accent-red);
}

.pin-input-group {
  display: flex;
  gap: 8px;
}

.pin-input-group input {
  flex: 1;
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid var(--glass-border);
  border-radius: 12px;
  padding: 0 12px;
  color: #fff;
  font-family: var(--font-family);
  font-size: 0.9rem;
  letter-spacing: 2px;
  outline: none;
}

.pin-input-group input:focus {
  border-color: var(--accent-cyan);
}

</style>
</head>
<body>
  <div class="background-glow"></div>
  
  <div class="remote-container">
    <!-- Header / Status Bar -->
    <header class="remote-header">
      <div class="brand">
        <span class="brand-title">XGIMI</span>
        <span class="brand-sub">BLE REMOTE</span>
      </div>
      <div class="header-actions">
        <button class="btn-icon" id="openPairingBtn" title="Pairing & Accessories">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M11,7V13H13V7H11M11,15V17H13V15H11Z"/></svg>
        </button>
        <div class="status-pill" id="statusPill">
          <span class="status-dot"></span>
          <span class="status-text" id="statusText">Connecting...</span>
        </div>
      </div>
    </header>

    <!-- Top Action Buttons (Power, Settings, Source, Mute) -->
    <div class="top-bar">
      <button class="btn btn-power" data-action="KPPOWER" title="Power">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M13,3H11V13H13M17.83,5.17L16.41,6.59C18.05,7.91 19,9.9 19,12A7,7 0 0,1 12,19A7,7 0 0,1 5,12C5,9.9 5.95,7.91 7.58,6.58L6.17,5.17C4.21,6.82 3,9.26 3,12A9,9 0 0,0 12,21A9,9 0 0,0 21,12C21,9.26 19.79,6.82 17.83,5.17Z"/></svg>
      </button>
      <button class="btn btn-glass" data-action="XGIMI_MISCKEY" title="Projector Settings">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M12,15.5A3.5,3.5 0 0,1 8.5,12A3.5,3.5 0 0,1 12,8.5A3.5,3.5 0 0,1 15.5,12A3.5,3.5 0 0,1 12,15.5M19.43,12.97C19.47,12.65 19.5,12.33 19.5,12C19.5,11.67 19.47,11.34 19.43,11L21.54,9.37C21.73,9.22 21.78,8.95 21.66,8.73L19.66,5.27C19.54,5.05 19.27,4.96 19.05,5.05L16.56,6.05C16.04,5.66 15.5,5.32 14.87,5.07L14.49,2.42C14.46,2.18 14.25,2 14,2H10C9.75,2 9.54,2.18 9.51,2.42L9.13,5.07C8.5,5.32 7.96,5.66 7.44,6.05L4.95,5.05C4.73,4.96 4.46,5.05 4.34,5.27L2.34,8.73C2.21,8.95 2.27,9.22 2.46,9.37L4.57,11C4.53,11.34 4.5,11.67 4.5,12C4.5,12.33 4.53,12.65 4.57,12.97L2.46,14.63C2.27,14.78 2.21,15.05 2.34,15.27L4.34,18.73C4.46,18.95 4.73,19.03 4.95,18.95L7.44,17.94C7.96,18.34 8.5,18.68 9.13,18.93L9.51,21.58C9.54,21.82 9.75,22 10,22H14C14.25,22 14.46,21.82 14.49,21.58L14.87,18.93C15.5,18.68 16.04,18.34 16.56,17.94L19.05,18.95C19.27,19.03 19.54,18.95 19.66,18.73L21.66,15.27C21.78,15.05 21.73,14.78 21.54,14.63L19.43,12.97Z"/></svg>
      </button>
      <button class="btn btn-glass" data-action="XGIMI_SOURCE" title="Input Source">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M21,3H3A2,2 0 0,0 1,5V19A2,2 0 0,0 3,21H21A2,2 0 0,0 23,19V5A2,2 0 0,0 21,3M21,19H3V5H21V19M16,16L20,12L16,8V11H8V13H16V16Z"/></svg>
      </button>
      <button class="btn btn-glass" data-action="KPPOWER" title="Mute Toggle">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M12,4L9.91,6.09L12,8.18M4.27,3L3,4.27L7.73,9H3V15H7L12,20V13.27L16.25,17.53C15.58,18.04 14.83,18.46 14,18.7V20.77C15.38,20.45 16.63,19.82 17.68,18.96L19.73,21L21,19.73L4.27,3M19,12C19,12.94 18.8,13.82 18.46,14.64L19.97,16.15C20.62,14.91 21,13.5 21,12C21,7.72 18,4.14 14,3.23V5.29C16.89,6.15 19,8.83 19,12M16.5,12C16.5,10.23 15.5,8.71 14,7.97V10.18L16.45,12.63C16.48,12.43 16.5,12.21 16.5,12Z"/></svg>
      </button>
    </div>

    <!-- Special XGIMI Focus Control Panel -->
    <section class="focus-card">
      <div class="card-header">
        <span class="card-title">XGIMI FOCUS ENGINE</span>
      </div>
      <div class="focus-grid">
        <button class="btn btn-accent btn-autofocus" data-action="FOCUS_AUTO">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M12,6A6,6 0 0,0 6,12A6,6 0 0,0 12,18A6,6 0 0,0 18,12A6,6 0 0,0 12,6M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z"/></svg>
          <span>AUTOFOCUS</span>
        </button>

        <button class="btn btn-secondary btn-manualfocus" data-action="FOCUS_MAN_NEW">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,17A5,5 0 0,1 7,12A5,5 0 0,1 12,7A5,5 0 0,1 17,12A5,5 0 0,1 12,17Z"/></svg>
          <span>MANUAL FOCUS</span>
        </button>

        <button class="btn btn-stepper" data-action="FOCUS_LEFT" title="Focus Left">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z"/></svg>
          <span>FOCUS -</span>
        </button>

        <button class="btn btn-stepper" data-action="FOCUS_RIGHT" title="Focus Right">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z"/></svg>
          <span>FOCUS +</span>
        </button>
      </div>
    </section>

    <!-- Navigation D-Pad Ring -->
    <div class="dpad-wrapper">
      <div class="dpad-ring">
        <button class="dpad-btn dpad-up" data-action="DPAD_UP" title="Up">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M7.41,15.41L12,10.83L16.59,15.41L18,14L12,8L6,14L7.41,15.41Z"/></svg>
        </button>
        <button class="dpad-btn dpad-left" data-action="DPAD_LEFT" title="Left">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z"/></svg>
        </button>
        <button class="dpad-btn dpad-center" data-action="DPAD_CENTER" title="OK / Select">
          <span>OK</span>
        </button>
        <button class="dpad-btn dpad-right" data-action="DPAD_RIGHT" title="Right">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z"/></svg>
        </button>
        <button class="dpad-btn dpad-down" data-action="DPAD_DOWN" title="Down">
          <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
        </button>
      </div>
    </div>

    <!-- Android / Remote Function Keys (Back, Home, Menu, Voice) -->
    <div class="function-row">
      <button class="btn btn-pill" data-action="BACK" title="Back">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M20,11H7.83L13.42,5.41L12,4L4,12L12,20L13.41,18.59L7.83,13H20V11Z"/></svg>
        <span>BACK</span>
      </button>

      <button class="btn btn-pill" data-action="HOME" title="Home">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z"/></svg>
        <span>HOME</span>
      </button>

      <button class="btn btn-pill" data-action="MENU" title="Menu">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z"/></svg>
        <span>MENU</span>
      </button>

      <button class="btn btn-pill btn-voice" data-action="VOICE_ASSIST" title="Voice Assistant">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M12,2A3,3 0 0,1 15,5V11A3,3 0 0,1 12,14A3,3 0 0,1 9,11V5A3,3 0 0,1 12,2M19,11C19,14.53 16.39,17.44 13,17.93V21H11V17.93C7.61,17.44 5,14.53 5,11H7A5,5 0 0,0 12,16A5,5 0 0,0 17,11H19Z"/></svg>
        <span>VOICE</span>
      </button>
    </div>

    <!-- Volume Control Bar -->
    <div class="volume-bar">
      <button class="btn btn-vol" data-action="VOLUME_DOWN" title="Volume Down">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M5,9V15H9L14,20V4L9,9H5M11,15.83L8.83,13.66H7V10.34H8.83L11,8.17V15.83Z"/></svg>
        <span>VOL -</span>
      </button>
      <div class="vol-indicator">VOLUME</div>
      <button class="btn btn-vol" data-action="VOLUME_UP" title="Volume Up">
        <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M14,3.23V5.29C16.89,6.15 19,8.83 19,12C19,15.17 16.89,17.84 14,18.7V20.77C18,19.86 21,16.28 21,12C21,7.72 18,4.14 14,3.23M16.5,12C16.5,10.23 15.5,8.71 14,7.97V16.02C15.5,15.29 16.5,13.76 16.5,12M3,9V15H7L12,20V4L7,9H3Z"/></svg>
        <span>VOL +</span>
      </button>
    </div>

    <!-- Footer Information -->
    <footer class="remote-footer">
      <span>Target: Vendor 0x000D / PID 0x3838</span>
    </footer>
  </div>

  <!-- Pairing Management Modal -->
  <div class="modal-overlay" id="pairingModal">
    <div class="modal-card">
      <div class="modal-header">
        <span class="modal-title">PAIRING & ACCESSORIES</span>
        <button class="btn-close" id="closePairingBtn">&times;</button>
      </div>

      <div class="modal-body">
        <div class="pair-status-box">
          <div class="pair-status-header">
            <span class="status-indicator-dot" id="modalStatusDot"></span>
            <span class="pair-status-state" id="modalStatusText">Checking BLE Status...</span>
          </div>
          <div class="pair-info-row">
            <span>Bonded Devices:</span> <strong id="modalBondedCount">0</strong>
          </div>
          <div class="pair-info-row">
            <span>Peer Address:</span> <strong id="modalPeerAddr">None</strong>
          </div>
        </div>

        <!-- BLE Pairing Actions -->
        <div class="action-section">
          <span class="section-title">BLUETOOTH REMOTE PAIRING</span>
          <button class="btn btn-modal btn-action-primary" id="startPairingBtn">
            <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M11,7V13H13V7H11M11,15V17H13V15H11Z"/></svg>
            <span>Start BLE Pairing Mode</span>
          </button>
          
          <button class="btn btn-modal btn-action-danger" id="clearBondsBtn">
            <svg viewBox="0 0 24 24" class="icon"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z"/></svg>
            <span>Clear Saved Bluetooth Bonds</span>
          </button>
        </div>

        <!-- Wi-Fi PIN Pairing Input -->
        <div class="action-section">
          <span class="section-title">WI-FI TV REMOTE PIN AUTHENTICATION</span>
          <div class="pin-input-group">
            <input type="text" id="pinInput" maxlength="6" placeholder="Enter PIN code" autocomplete="off" />
            <button class="btn btn-modal btn-action-primary" id="submitPinBtn">Pair PIN</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
/**
 * XGIMI ESP32 BLE Remote & Pairing Web Application
 */

document.addEventListener('DOMContentLoaded', () => {
  const statusPill = document.getElementById('statusPill');
  const statusText = document.getElementById('statusText');
  const openPairingBtn = document.getElementById('openPairingBtn');
  const closePairingBtn = document.getElementById('closePairingBtn');
  const pairingModal = document.getElementById('pairingModal');

  const modalStatusDot = document.getElementById('modalStatusDot');
  const modalStatusText = document.getElementById('modalStatusText');
  const modalBondedCount = document.getElementById('modalBondedCount');
  const modalPeerAddr = document.getElementById('modalPeerAddr');

  const startPairingBtn = document.getElementById('startPairingBtn');
  const clearBondsBtn = document.getElementById('clearBondsBtn');
  const pinInput = document.getElementById('pinInput');
  const submitPinBtn = document.getElementById('submitPinBtn');

  let socket = null;
  let isConnected = false;

  // Initialize WebSocket or HTTP polling fallback
  function initConnection() {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = `${protocol}//${window.location.host}/ws`;

    try {
      socket = new WebSocket(wsUrl);

      socket.onopen = () => {
        setConnectedState(true, 'Connected');
        fetchPairingStatus();
      };

      socket.onclose = () => {
        setConnectedState(false, 'Reconnecting...');
        setTimeout(initConnection, 2000);
      };

      socket.onerror = () => {
        setConnectedState(false, 'HTTP Fallback Mode');
      };

      socket.onmessage = (event) => {
        try {
          const msg = JSON.parse(event.data);
          if (msg.type === 'pairing_status') {
            updatePairingUI(msg);
          } else if (msg.status === 'ble_connected') {
            setConnectedState(true, 'BLE Connected');
          } else if (msg.status === 'ble_disconnected') {
            setConnectedState(false, 'BLE Disconnected');
          }
        } catch (e) {
          console.log('WS msg:', event.data);
        }
      };
    } catch (err) {
      setConnectedState(false, 'HTTP Mode');
    }
  }

  function setConnectedState(connected, text) {
    isConnected = connected;
    statusText.textContent = text;
    if (connected) {
      statusPill.classList.remove('disconnected');
      statusPill.classList.add('connected');
    } else {
      statusPill.classList.remove('connected');
      statusPill.classList.add('disconnected');
    }
  }

  function updatePairingUI(status) {
    modalBondedCount.textContent = status.bonded_count ?? 0;
    modalPeerAddr.textContent = status.peer_address ?? 'None';

    if (status.connected) {
      modalStatusText.textContent = 'Paired & Connected to Projector';
      modalStatusDot.style.backgroundColor = '#00e676';
    } else if (status.advertising) {
      modalStatusText.textContent = 'BLE Pairing Mode Active (Discoverable)';
      modalStatusDot.style.backgroundColor = '#00f2fe';
    } else {
      modalStatusText.textContent = 'Not Connected / Idle';
      modalStatusDot.style.backgroundColor = '#ff4b4b';
    }
  }

  function fetchPairingStatus() {
    fetch('/api/pair/status')
      .then(res => res.json())
      .then(data => updatePairingUI(data))
      .catch(err => console.error('Failed fetching pairing status:', err));
  }

  // Send action to ESP32
  function triggerAction(actionName) {
    if ('vibrate' in navigator) {
      navigator.vibrate(25);
    }

    if (socket && socket.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'key_press', action: actionName }));
    } else {
      fetch(`/api/press?action=${encodeURIComponent(actionName)}`, { method: 'POST' })
        .catch(err => console.error('Failed sending key press:', err));
    }
  }

  // Pairing Modal Event Handlers
  openPairingBtn.addEventListener('click', () => {
    pairingModal.classList.add('open');
    fetchPairingStatus();
  });

  closePairingBtn.addEventListener('click', () => {
    pairingModal.classList.remove('open');
  });

  pairingModal.addEventListener('click', (e) => {
    if (e.target === pairingModal) {
      pairingModal.classList.remove('open');
    }
  });

  startPairingBtn.addEventListener('click', () => {
    fetch('/api/pair/start', { method: 'POST' })
      .then(res => res.json())
      .then(data => {
        alert('BLE Pairing Mode Enabled for 60s! On your XGIMI Projector, go to Settings -> Remotes & Accessories -> Add Accessory and select XGIMIRC.');
        fetchPairingStatus();
      })
      .catch(err => alert('Failed starting BLE pairing mode: ' + err));
  });

  clearBondsBtn.addEventListener('click', () => {
    if (confirm('Are you sure you want to clear all stored Bluetooth bonds?')) {
      fetch('/api/pair/clear', { method: 'POST' })
        .then(res => res.json())
        .then(data => {
          alert('Cleared all saved Bluetooth bonds!');
          fetchPairingStatus();
        })
        .catch(err => alert('Failed clearing bonds: ' + err));
    }
  });

  submitPinBtn.addEventListener('click', () => {
    const pin = pinInput.value.trim();
    if (!pin) {
      alert('Please enter a PIN code.');
      return;
    }
    fetch('/api/pair/pin', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: `pin=${encodeURIComponent(pin)}`
    })
      .then(res => res.json())
      .then(data => {
        alert(`PIN '${pin}' submitted successfully!`);
        pinInput.value = '';
      })
      .catch(err => alert('Failed submitting PIN: ' + err));
  });

  // Attach event listeners to all remote buttons
  const buttons = document.querySelectorAll('[data-action]');
  buttons.forEach(button => {
    const actionName = button.getAttribute('data-action');
    
    button.addEventListener('pointerdown', (e) => {
      e.preventDefault();
      button.classList.add('active');
      triggerAction(actionName);
    });

    button.addEventListener('pointerup', () => {
      button.classList.remove('active');
    });

    button.addEventListener('pointerleave', () => {
      button.classList.remove('active');
    });
  });

  // Physical Keyboard shortcut support
  window.addEventListener('keydown', (e) => {
    if (e.repeat) return;
    let action = null;
    switch (e.key) {
      case 'ArrowUp': action = 'DPAD_UP'; break;
      case 'ArrowDown': action = 'DPAD_DOWN'; break;
      case 'ArrowLeft': action = 'DPAD_LEFT'; break;
      case 'ArrowRight': action = 'DPAD_RIGHT'; break;
      case 'Enter': action = 'DPAD_CENTER'; break;
      case 'Escape': case 'Backspace': action = 'BACK'; break;
      case 'Home': action = 'HOME'; break;
      case 'm': case 'M': action = 'MENU'; break;
      case 'f': case 'F': action = 'FOCUS_AUTO'; break;
      case 'g': case 'G': action = 'FOCUS_MAN_NEW'; break;
      case '[': action = 'FOCUS_LEFT'; break;
      case ']': action = 'FOCUS_RIGHT'; break;
      case 's': case 'S': action = 'XGIMI_MISCKEY'; break;
      case '+': action = 'VOLUME_UP'; break;
      case '-': action = 'VOLUME_DOWN'; break;
    }
    if (action) {
      const btn = document.querySelector(`[data-action="${action}"]`);
      if (btn) {
        btn.classList.add('active');
        setTimeout(() => btn.classList.remove('active'), 200);
      }
      triggerAction(action);
    }
  });

  initConnection();
});

</script>
</body>
</html>

)rawliteral";

#endif // WEB_ASSETS_H
