/* Auto-generated by scripts/generate_keymap.py - DO NOT EDIT MANUALLY */
#ifndef XGIMI_KEYMAP_H
#define XGIMI_KEYMAP_H

#include <stdint.h>

// XGIMI Remote Vendor ID & Product ID
#define XGIMI_VENDOR_ID  0x000D
#define XGIMI_PRODUCT_ID 0x3838
#define XGIMI_DEVICE_NAME "XGIMI-RC-pseudo"

struct XGIMIKeyMapping {
    const char* actionName;
    uint16_t linuxCode;
    uint8_t hidPage;   // 0x07 = Keyboard, 0x0C = Consumer Control
    uint16_t hidCode;
    const char* description;
};

static const XGIMIKeyMapping XGIMI_KEYMAP[] = {
    { "DPAD_CENTER", 28, 0x7, 0x28, "OK / Select" },
    { "DPAD_CENTER", 353, 0x7, 0x28, "OK / Select" },
    { "FOCUS_AUTO", 87, 0x7, 0x44, "Autofocus" },
    { "FOCUS_LEFT", 67, 0x7, 0x42, "Manual Focus Left" },
    { "FOCUS_RIGHT", 68, 0x7, 0x43, "Manual Focus Right" },
    { "HOME", 102, 0x7, 0x4a, "Home" },
    { "DPAD_UP", 103, 0x7, 0x52, "D-Pad Up" },
    { "DPAD_LEFT", 105, 0x7, 0x50, "D-Pad Left" },
    { "DPAD_RIGHT", 106, 0x7, 0x4f, "D-Pad Right" },
    { "DPAD_DOWN", 108, 0x7, 0x51, "D-Pad Down" },
    { "KPPOWER", 116, 0xc, 0x30, "Power" },
    { "KPPOWER", 113, 0xc, 0xe2, "Mute" },
    { "VOLUME_DOWN", 114, 0xc, 0xea, "Volume Down" },
    { "VOLUME_UP", 115, 0xc, 0xe9, "Volume Up" },
    { "BACK", 1, 0x7, 0x29, "Back / ESC" },
    { "BACK", 158, 0x7, 0x29, "Back" },
    { "HOME", 172, 0x7, 0x4a, "Home" },
    { "VOICE_ASSIST", 217, 0xc, 0x221, "Voice Assistant" },
    { "MENU", 240, 0x7, 0x65, "Menu" },
    { "RC_LOW_BATTERY", 88, 0x7, 0x45, "RC Low Battery" },
    { "XGIMI_MISCKEY", 66, 0x7, 0x41, "Projector Settings" },
    { "XGIMI_SOURCE", 65, 0x7, 0x40, "Source Input" },
    { "FOCUS_MAN_NEW", 62, 0x7, 0x3d, "Manual Focus" },
};

static const size_t XGIMI_KEYMAP_SIZE = sizeof(XGIMI_KEYMAP) / sizeof(XGIMI_KEYMAP[0]);

#endif // XGIMI_KEYMAP_H
